use_frameworks!
target 'MemexSwiftSDK_Tests' do
  pod 'MemexSwiftSDK', :path => '../'
  
  pod 'ObjectMapper', '~> 3.0.0'
  pod 'ReachabilitySwift', '~> 4.0-beta2'
  pod 'KeychainSwift', '~> 9.0'
  
end
