

public extension Spaces {
  
  /**
   Authenticate user with credentials (email and password). Method will request user token and store it in KeyChain.
   
   Example:
   ```
   let credentials = new Credentials("email@host.com","secretPASSWORD")
   memex.loginUserWithUserCredentials(credentials) { error in
     guard error == nil else {
       // login failed
     }
     // login succeeded
   }
   
   ```
   
   - parameters:
     - credentials: Object that contains pair of email and password.
     - completion: Completion block that returns error if something wrong happens.
   
   */
  public func loginUserWithUserCredentials(
    credentials: Credentials,
    completion: @escaping RetryOutputs) {
    let completion = { (token: String?, retryToken: String?, error: Swift.Error?) -> Void in
      if error == nil {
        completion(retryToken, nil)
      } else {
        completion(retryToken, error)
      }
    }
    self.auth.authorizeWithCredentials(credentials: credentials,
                                       completionHandler: completion)
  }
  
  
  /**
   This method allows client to login with onboarding token. Method will request user token and store it in KeyChain.
   
   Example:
   ```
   memex.loginUserWithOnboardingToken("YourOnboardingToken") { error in
     guard error == nil else {
       // login failed
     }
     // login succeeded
   }
   
   ```
   
   - parameter token: Onboarding token that is generated on client or provided from icloud
   - parameter completion: Completion block that returns error if something wrong happens.
   
   */
  public func loginUserWithOnboardingToken(
    token: String,
    completion: @escaping RetryOutputs) {
    let completion = { (token: String?, retryToken: String?, error: Swift.Error?) -> Void in
      if error == nil {
        completion(retryToken, nil)
      } else {
        completion(retryToken, error)
      }
    }
    self.auth.authorizeWithOnboardingToken(token: token,
                                           completionHandler: completion)
  }
  
  /**
   This method allows client to login with two factor authentication retry token. Method will request user token and store it in KeyChain.
   
   - parameter token: Retry token that is generated by previous login attempt
   - parameter completion: Completion block that returns error
   
   */
  public func loginUserWithTFARetryToken(
    retryToken: String,
    completion: @escaping VoidOutputs) {
    let completion = { (token: String?, retryToken: String?, error: Swift.Error?) -> Void in
      if error == nil {
        completion(nil)
      } else {
        completion(error)
      }
    }
    self.auth.authorizeWithRetryToken(retryToken: retryToken,
                                      completionHandler: completion)
  }
  
  /**
   This method log out authenticated user. It removes user token from Keychain.
   
   - parameter completion: Completion block that returns error if something wrong happens.
   */
  public func logout(completion: @escaping VoidOutputs) {
    self.auth.deauthorize(completionHandler: completion)
  }

  
  /**
   This method log out authenticated user. It removes user token from Keychain.
   
   - parameter completion: Completion block provides user authentication status (true if user authentication token is present) and error message if something went wrong.
   - parameter loggedIn: True if user is logged in
   - parameter error: Error message
   */
  public func isLoggedIn(completion: (_ loggedIn: Bool?, _ error: Error?)->()) {
    completion(self.auth.userToken != nil, nil)
  }
  
  /**
   This function checks that password conforms to all requirements.
   
   - parameter password: Password to verify
   */
  public func verifyPassword(password: String?) -> Bool {
    guard let password = password else {
      return false
    }
    if password.count < 10 {
      return false
    }
    let containsUppercaseChars = NSPredicate(format:"SELF MATCHES %@", ".*[A-Z]+.*").evaluate(with: password)
    let containsLowercaseChars = NSPredicate(format:"SELF MATCHES %@", ".*[a-z]+.*").evaluate(with: password)
    let containsNumbers = NSPredicate(format:"SELF MATCHES %@", ".*[0-9]+.*").evaluate(with: password)
    if !containsLowercaseChars || !containsUppercaseChars || !containsNumbers {
      return false
    }
    return true
  }
  
  /**
   This function checks that onboarding token conforms to all requirements.
   
   - parameter token: Token to verify
   */
  public func verifyOnboardingToken(token: String?) -> Bool {
    guard let token = token else {
      return false
    }
    if token.count < 10 {
      return false
    }
    return true
  }
  
  
}

